name: Resolve Manifest Conflict 

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    paths:
      - 'StoryCAD/Package.appxmanifest'

jobs:
  resolve-conflict:
    runs-on: windows-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }} # Check out the incoming branch

    - name: jake debug
      run: |
        dir
        cd ${{ github.workspace }}
        Test-Path -Path .git
        
    - name: Resolve conflict in Package.appxmanifest
      run: |
        Set-Location ${{ github.workspace }}
        $conflicted = (git diff --name-only --diff-filter=U) -contains 'StoryCAD/Package.appxmanifest'
        if ($conflicted) {
          git checkout --theirs StoryCAD/Package.appxmanifest
          git add StoryCAD/Package.appxmanifest
          git commit -m "Resolved conflict in Package.appxmanifest by taking incoming changes"
        }
      shell: pwsh

    - name: Push changes if conflict resolved
      run: |
        Set-Location ${{ github.workspace }}
        if (git log -1 --pretty=%B -s | Select-String -Pattern "Resolved conflict in Package.appxmanifest by taking incoming changes") {
          git push origin ${{ github.event.pull_request.head.ref }}
        }
      shell: pwsh
